language: java

script: ./gradlew build

dist: trusty

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

jdk:
  - oraclejdk8

notifications:
  slack: reportportal-dev:fl6xWHVQp1jvsMmCJxYW9YKP

after_success:
  - bash <(curl -s https://codecov.io/bash)
