info:
  build:
    version: ${rp.uat.version:5.0}
server:
  port: 9999
security:
  oauth2:
    resource:
      filter-order: 3
spring:
  jackson:
    default-property-inclusion: non_null
  session:
    store-type: jdbc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${rp.db.url}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc.lob.non_contextual_creation: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  profiles:
    ## Profiles list
    active: ${rp.profiles:default}

logging:
  level:
    org.springframework.security: debug

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs


#### Custom ReportPortal Properties ######
##########################################
rp:
  db:
    url: jdbc:postgresql://${rp.db.host}:${rp.db.port}/reportportal?user=${rp.db.user}&password=${rp.db.pass}
    host: postgres
    port: 5432
    user: rpuser
    pass: rppass
  jwt:
    signing-key: 123
  auth:
    server: default