rp:
  db:
    host: localhost
  auth:
    saml:
      base-path: http://localhost:9999
  binarystore:
    type: minio
    minio:
      endpoint: http://localhost:9000
      accessKey: minio
      secretKey: minio123
    path: ${java.io.tmpdir}${file.separator}reportportal${file.separator}datastore
server:
  port: 9999
logging:
  level:
    org:
      hibernate:
        SQL: debug
