rp:
  db:
    host: localhost
  auth:
    saml:
      base-path: http://localhost:9999
  binarystore:
    type: filesystem
    path: ${java.io.tmpdir}\reportportal\datastore\
server:
  port: 9999
logging:
  level:
    org:
      hibernate:
        SQL: debug
