management:
  endpoints:
    web:
      base-path: /
info:
  build:
    name: Authorization Service
    description: Unified Authorization Trap for all ReportPortal's Services
    version: ${rp.uat.version:5.0}
server:
  port: 9999
  use-forward-headers: true
spring:
  application:
    name: uat
  jackson:
    default-property-inclusion: non_null
  session:
    store-type: jdbc
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc.lob.non_contextual_creation: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  profiles:
    ## Profiles list
    active: ${rp.profiles:default}

logging:
  level:
    org.springframework.security: debug

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs


#### Custom ReportPortal Properties ######
##########################################
rp:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    jdbcUrl: ${rp.db.url}
    username: ${rp.db.user}
    password: ${rp.db.pass}
    maximumPoolSize: 27

  db:
    url: jdbc:postgresql://${rp.db.host}:${rp.db.port}/${rp.db.name}
    name: reportportal
    host: postgres
    port: 5432
    user: rpuser
    pass: rppass
  jwt:
    signing-key: 123
    token:
      validity-period: 86400
  auth:
    server: default
  binarystore:
    path: /data/storage
    master:
      host: seaweed-master
      port: 9333
    minio:
      endpoint: http://play.min.io
      accessKey: Q3AM3UQ867SPQQA43P2F
      secretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    # could be one of [seaweed, filesystem, minio]
    type: filesystem
  plugins:
    service: uat
    rootDir: /plugins/auth
    resolved:
      path: ${rp.plugins.rootDir}/resolved
      resources: ${rp.plugins.rootDir}/resources
    temp:
      path: ${rp.plugins.rootDir}/temp