server:
  port: 9999
security:
  sessions: stateless
  oauth2:
    resource:
      filter-order: 3

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags:
          - urlprefix-${server.context-path:}/${spring.application.name} opts strip=/${spring.application.name}
          - traefik.frontend.rule=PathPrefixStrip:${server.context-path:}/${spring.application.name}
          - statusPageUrlPath=${server.contextPath:}/info
          - healthCheckUrlPath=${server.contextPath:}/health
        healthCheckPath: ${server.context-path:}/health
        register: true
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-critical-timeout: 180s
      enabled: true

  # Enable MongoDB repositories
  data:
    mongodb:
      repositories:
        enabled: true
  jackson:
    default-property-inclusion: non_null
  session:
    store-type: mongo


eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    status-page-url-path: ${server.contextPath:}/info
    health-check-url-path: ${server.contextPath:}/health
  ## Disabled by default
  client:
    register-with-eureka: false
    enabled: false

# MongoDB configuration
rp:
   session:
        live: 1800
   mongo:
        uri: mongodb://localhost:27017
        dbName: reportportal
        connectionsPerHost: 50
        threadsAllowedToBlockForConnectionMultiplier: 50
        connectTimeout: 20000
        socketTimeout: 60000
        maxWaitTime: 120000
        autoConnectRetry: true
        socketKeepAlive: true
        slaveOk: true
        writeTimeout: 0
        writeNumber: 1
        writeFsync: false
   cache:
        project:
          size: 1000
          expiration: 1
          info: 10
        ticket:
          size: 10000
          expiration: 5
        user:
          size: 1000
          expiration: 1
   auth:
        encryptor:
          password: reportportal
        saml:
          base-path: ${SP_BASE_PATH:${server.contextPath:http://localhost:8080}}/${spring.application.name}
          key-password: ${SP_KEY_PASSWORD:password}
          key-alias: ${SP_KEY_ALIAS:report-portal-sp}
          key-store: ${SP_KEY_STORE:saml/keystore.jks}
          key-store-password: ${SP_KEY_STORE_PASSWORD:password}
          network-connection-timeout: ${SP_NETWORK_CONNECTION_TIMEOUT:5000}
          network-read-timeout: ${SP_NETWORK_READ_TIMEOUT:10000}
          signed-requests: ${SP_SIGNED_REQUESTS:false}
          active-key-name: sp-signing-key


logging:
  level:
    org.springframework.security: warn
    org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexResolver: warn
    com.netflix.discovery.shared.resolver : warn

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

## Consul as service registry
---
spring:
  profiles: consul
  cloud:
    consul:
      enabled: true
      discovery:
        register: true
eureka:
  client:
    register-with-eureka: false
    enabled: false

## Eureka as service registry
---
spring:
  profiles: eureka
  cloud:
    consul:
      enabled: false
      discovery:
        register: false
eureka:
  client:
    register-with-eureka: true
    enabled: true
---
