
spring:
  cloud:
    consul:
      discovery:
        hostname: docker.for.mac.localhost
      host: localhost

rp:
  amqp:
    addresses: amqp://rabbitmq:rabbitmq@localhost:5672
  db:
    url: jdbc:postgresql://localhost:5432/reportportal?user=rpuser&password=rppass
server:
  port: 9999